"""initial_schema

Revision ID: 592a92c76665
Revises: 
Create Date: 2026-04-22 09:49:11.945975

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '592a92c76665'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('documento', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('logradouro', sa.String(length=100), nullable=True),
    sa.Column('numero', sa.String(length=10), nullable=True),
    sa.Column('bairro', sa.String(length=50), nullable=True),
    sa.Column('municipio_nome', sa.String(length=50), nullable=True),
    sa.Column('uf', sa.String(length=2), nullable=True),
    sa.Column('cep', sa.String(length=8), nullable=True),
    sa.Column('data_cadastro', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clientes_documento'), 'clientes', ['documento'], unique=True)
    op.create_index(op.f('ix_clientes_id'), 'clientes', ['id'], unique=False)
    op.create_table('empresas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cnpj', sa.String(length=14), nullable=False),
    sa.Column('razao_social', sa.String(length=255), nullable=False),
    sa.Column('inscricao_estadual', sa.String(length=20), nullable=False),
    sa.Column('logradouro', sa.String(length=255), nullable=True),
    sa.Column('numero', sa.String(length=20), nullable=True),
    sa.Column('bairro', sa.String(length=100), nullable=True),
    sa.Column('municipio_ibge', sa.String(length=7), nullable=True),
    sa.Column('municipio_nome', sa.String(length=100), nullable=True),
    sa.Column('uf', sa.String(length=2), nullable=True),
    sa.Column('cep', sa.String(length=8), nullable=True),
    sa.Column('ambiente', sa.Integer(), nullable=True),
    sa.Column('certificado_path', sa.String(length=255), nullable=True),
    sa.Column('certificado_senha', sa.String(length=255), nullable=True),
    sa.Column('csc_token', sa.String(length=100), nullable=True),
    sa.Column('csc_id', sa.String(length=10), nullable=True),
    sa.Column('pix_chave', sa.String(length=100), nullable=True),
    sa.Column('configurado', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_empresas_cnpj'), 'empresas', ['cnpj'], unique=True)
    op.create_index(op.f('ix_empresas_id'), 'empresas', ['id'], unique=False)
    op.create_table('produtos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo_barras', sa.String(length=13), nullable=True),
    sa.Column('plu', sa.Integer(), nullable=True),
    sa.Column('descricao', sa.String(length=255), nullable=False),
    sa.Column('preco_venda', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('unidade', sa.String(length=10), nullable=True),
    sa.Column('categoria', sa.Enum('BEBIDA', 'REFEICAO', 'OUTROS', name='categoriaenum'), nullable=True),
    sa.Column('imagem_url', sa.String(length=255), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('ncm', sa.String(length=8), nullable=False),
    sa.Column('cest', sa.String(length=7), nullable=True),
    sa.Column('cfop', sa.String(length=4), nullable=False),
    sa.Column('origem', sa.String(length=1), nullable=True),
    sa.Column('cst_icms', sa.String(length=3), nullable=True),
    sa.Column('cst_pis', sa.String(length=2), nullable=True),
    sa.Column('cst_cofins', sa.String(length=2), nullable=True),
    sa.Column('aliquota_pis', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('aliquota_cofins', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('aliquota_icms', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_produtos_id'), 'produtos', ['id'], unique=False)
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('is_active', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    op.create_index(op.f('ix_usuarios_username'), 'usuarios', ['username'], unique=True)
    op.create_table('vendas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mesa', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ABERTA', 'AGUARDANDO_PAGAMENTO', 'PAGA', 'CANCELADA', name='statusvenda'), nullable=True),
    sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('data_abertura', sa.DateTime(), nullable=True),
    sa.Column('data_fechamento', sa.DateTime(), nullable=True),
    sa.Column('forma_pagamento', sa.Enum('PIX', 'DINHEIRO', 'CARTAO_CREDITO', 'CARTAO_DEBITO', name='formapagamento'), nullable=True),
    sa.Column('pix_payload', sa.String(length=512), nullable=True),
    sa.Column('pix_expiracao', sa.DateTime(), nullable=True),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_venda_ativa_mesa', 'vendas', ['mesa'], unique=True, postgresql_where=sa.text("status IN ('ABERTA', 'AGUARDANDO_PAGAMENTO')"))
    op.create_index(op.f('ix_vendas_id'), 'vendas', ['id'], unique=False)
    op.create_table('notas_fiscais',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('venda_id', sa.Integer(), nullable=False),
    sa.Column('chave_acesso', sa.String(length=44), nullable=True),
    sa.Column('numero_nota', sa.Integer(), nullable=True),
    sa.Column('serie_nota', sa.Integer(), nullable=True),
    sa.Column('protocolo', sa.String(length=50), nullable=True),
    sa.Column('status_sefaz', sa.String(length=10), nullable=True),
    sa.Column('motivo_sefaz', sa.String(length=255), nullable=True),
    sa.Column('xml_autorizado', sa.Text(), nullable=True),
    sa.Column('protocolo_cancelamento', sa.String(length=50), nullable=True),
    sa.Column('motivo_cancelamento', sa.String(length=255), nullable=True),
    sa.Column('data_cancelamento', sa.DateTime(), nullable=True),
    sa.Column('data_emissao', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['venda_id'], ['vendas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chave_acesso'),
    sa.UniqueConstraint('venda_id')
    )
    op.create_index(op.f('ix_notas_fiscais_id'), 'notas_fiscais', ['id'], unique=False)
    op.create_table('venda_itens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('venda_id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=True),
    sa.Column('preco_unitario', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('ncm', sa.String(length=8), nullable=True),
    sa.Column('cest', sa.String(length=7), nullable=True),
    sa.Column('cfop', sa.String(length=4), nullable=True),
    sa.Column('origem', sa.String(length=1), nullable=True),
    sa.Column('cst_icms', sa.String(length=3), nullable=True),
    sa.Column('cst_pis', sa.String(length=2), nullable=True),
    sa.Column('cst_cofins', sa.String(length=2), nullable=True),
    sa.Column('aliquota_pis', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('aliquota_cofins', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('aliquota_icms', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], ),
    sa.ForeignKeyConstraint(['venda_id'], ['vendas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_venda_itens_id'), 'venda_itens', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_venda_itens_id'), table_name='venda_itens')
    op.drop_table('venda_itens')
    op.drop_index(op.f('ix_notas_fiscais_id'), table_name='notas_fiscais')
    op.drop_table('notas_fiscais')
    op.drop_index(op.f('ix_vendas_id'), table_name='vendas')
    op.drop_index('idx_venda_ativa_mesa', table_name='vendas', postgresql_where=sa.text("status IN ('ABERTA', 'AGUARDANDO_PAGAMENTO')"))
    op.drop_table('vendas')
    op.drop_index(op.f('ix_usuarios_username'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_produtos_id'), table_name='produtos')
    op.drop_table('produtos')
    op.drop_index(op.f('ix_empresas_id'), table_name='empresas')
    op.drop_index(op.f('ix_empresas_cnpj'), table_name='empresas')
    op.drop_table('empresas')
    op.drop_index(op.f('ix_clientes_id'), table_name='clientes')
    op.drop_index(op.f('ix_clientes_documento'), table_name='clientes')
    op.drop_table('clientes')
    # ### end Alembic commands ###
