"""Add vendas and fiscal tables

Revision ID: 867303402143
Revises: 30e416bc35f5
Create Date: 2026-04-15 21:54:23.071539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '867303402143'
down_revision: Union[str, Sequence[str], None] = '30e416bc35f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_empresas_cnpj'), table_name='empresas')
    op.drop_index(op.f('ix_empresas_id'), table_name='empresas')
    op.drop_table('empresas')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empresas',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('cnpj', sa.VARCHAR(length=14), autoincrement=False, nullable=False),
    sa.Column('razao_social', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('inscricao_estadual', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('logradouro', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('numero', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('bairro', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('municipio_ibge', sa.VARCHAR(length=7), autoincrement=False, nullable=True),
    sa.Column('municipio_nome', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('uf', sa.VARCHAR(length=2), autoincrement=False, nullable=True),
    sa.Column('cep', sa.VARCHAR(length=8), autoincrement=False, nullable=True),
    sa.Column('ambiente', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('certificado_path', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('certificado_senha', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('csc_token', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('csc_id', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('configurado', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('empresas_pkey'))
    )
    op.create_index(op.f('ix_empresas_id'), 'empresas', ['id'], unique=False)
    op.create_index(op.f('ix_empresas_cnpj'), 'empresas', ['cnpj'], unique=True)
    # ### end Alembic commands ###
