"""Add xml_enviado e xml_recebido to notas_fiscais

Revision ID: e110634bbad6
Revises: 60e3b4d5c6e7
Create Date: 2026-04-22 19:10:59.427857

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e110634bbad6'
down_revision: Union[str, Sequence[str], None] = '60e3b4d5c6e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notas_fiscais', sa.Column('xml_enviado', sa.Text(), nullable=True))
    op.add_column('notas_fiscais', sa.Column('xml_recebido', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notas_fiscais', 'xml_recebido')
    op.drop_column('notas_fiscais', 'xml_enviado')
    # ### end Alembic commands ###
